# Shell
shell /usr/bin/fish

# Mod key
kitty_mod ctrl+shift


# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# END_KITTY_THEME

# Fonts
font_family Firacode Nerd Font
bold_font Firacode Nerd Font Bold
italic_font Firacode Nerd Font Italic
bold_italic_font Firacode Nerd Font Bold Italic
font_size 16

# Opacity
background_opacity 0.90

# Window
window_margin_width 7
window_border_width 2pt
single_window_margin_width 2

# Tab
tab_bar_style powerline

# Key map
map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+l neighboring_window right
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard

